#!/bin/sh
# vim: set fileencoding=utf-8 ai noet sts=8 sw=8 tw=0:
#
# Copyright © 2009 Stephen Gran <sgran@debian.org>
# Copyright © 2010 Martin Zobel-Helas <zobel@debian.org>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

FILE=''
EXIT=0
LEVEL=''

usage(){
	ret=$1

	cat <<EOF
$0: usage:
	$0 <options>

	File checker for nagios.  Will alert if the named file does not exist

	-h	This help message
	-w	If the file does not exist, this is only warning
	-f	File to check
EOF

	exit $ret
}

while getopts f:hw opt ; do
	case "$opt" in
		f) FILE="$OPTARG" ;;
		w) LEVEL="WARNING";;
		h) usage 0
	esac
done

if [ "$LEVEL" = "WARNING" ]; then
	EXIT=1
else
	EXIT=2
	LEVEL="CRITICAL"
fi

if [ -z "$FILE" ]; then
	echo "Need file argument!" >&2
	usage 3
fi

if [ ! -f "$FILE" ]; then
	printf "%s: file %s is missing\n" $LEVEL $FILE
	exit $EXIT
fi

printf "OK: file %s does exist %s\n" $FILE
