#! /bin/bash
#
# Copyright 2009 Stephen Gran <sgran@debian.org>
# Copyright 2010 Peter Palfrader
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

usage(){
	ret=$1
	exit $ret
}

host="$1"
if [ -z "$host" ] || [ "$host" = "-h" ] ||  [ "$host" = "--help" ]; then
	echo >&2 "Usage: $0 <host>"
	usage 3
fi

if [ "${host/[^a-z0-9]/}" != "$host" ]; then
	echo >&2 "$0: Invalid hostname $1"
	exit 3
fi

ts=$(date -d 'now' +'%Y/%m/%d')
file="/var/log/hosts/$host/$ts/syslog"
if [ ! -e "$file" ]; then
	# maybe we did not log anything today yet?
	ts=$(date -d 'now - 1 hour' +'%Y/%m/%d')
	file="/var/log/hosts/$host/$ts/syslog"
fi

if [ ! -e "$file" ]; then
	echo "log file $file is missing"
	exit 2
fi

if [ "$( date -d 'now - 60 minutes' +%s )" -gt "$(stat -c %Y "$file" )" ]; then
	echo "log file $file is older than 60 minutes"
	exit 2
fi

printf "log file %s OK: last changed %s\n" $file "$(stat -c %y $file)"
