#!/bin/sh

check=/usr/lib/nagios/plugins/dsa-check-bacula-lastbackup
usage() {
	echo >&2 "Usage: $0 <full|any> <host> [warn age [critical age (hours)]]"
	exit 1
}

if [ "$#" -lt 2 ] || [ "$#" -gt 4 ]; then
	usage
fi

if [ "$1" = "full" ]; then
	level="F"
	crit=1560
	warn=840
elif [ "$1" = "any" ]; then
	level="*"
	crit=60
	warn=36
else
	usage
fi

if [ "$#" -ge 3 ]; then warn="$3"; fi
if [ "$#" -ge 4 ]; then crit="$4"; fi


exec "$check" -level="$level" -warningAge="$warn" -criticalAge="$crit" -client="$2.debian.org"
