#!/bin/sh

# Check that debian-admin is in /etc/aliases for root.
# Peter Palfrader, 2008

#my %ERRORS = ( OK => 0, WARNING => 1, CRITICAL => 2, UNKNOWN => -1 );

set -e

if ! [ -e /etc/aliases ]; then
	echo "UNKNOWN: /etc/aliases not found"
	exit 3
fi

if egrep '^root:.*debian-admin@debian.org' /etc/aliases > /dev/null; then
	echo "OK: debian-admin found in aliases"
	exit 0
fi

echo "WARNING: debian-admin not found in root entry in aliases"
exit 1
